apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-new-app
  template:
    metadata:
      labels:
        app: my-new-app
    spec:
      containers:
      - name: my-new-app
        image: my-new-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
         
---
apiVersion: v1
kind: Service
metadata:
  name: my-new-app
spec:
  selector:
    app: my-new-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: NodePort
