apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-new-app
  template:
    metadata:
      labels:
        app: my-new-app
    spec:
      containers:
        - name: my-new-app
          image: my-new-app
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: my-new-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: my-new-app
