apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-new-app
  template:
    metadata:
      labels:
        app: my-new-app
    spec:
      containers:
      - name: my-new-app
        image: my-new-app:latest
        ports:
        - containerPort: 8070
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8070
            env:
            - name: PORT
              value: "8070"
---
apiVersion: v1
kind: Service
metadata:
  name: my-new-app
spec:
  selector:
    app: my-new-app
  ports:
  - name: http
    port: 80
    targetPort: 8070
  type: NodePort
